import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Header from "../components/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {children: React.ReactNode}) {
  const {children} = props
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased h-screen w-screen`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
